### ISSUE TITLE
【BUG】Deprecated: Array and string offset access syntax with curly braces is deprecated in /www/wwwroot/Wikitten/renderers/Markdown/Markdown.php on line 1799

### ISSUE THREAD

**Issue by tianheg** [devaneando/Wikitten#108]
Just like the title. There are many errors like this, I just change it one by one.

These errors are located in Wikitten/renderers/Markdown/Markdown.php and Wikitten/renderers/Markdown/MarkdownExtra.php.

The way I alter is changing `{}` to `[]`.  That's all the mistakes.

 This is my server configuration:
BTpanel:It is a  simple Installation Panel.
Through it I install 
* Nginx 1.16.1
* MySQL 5.5.62
* PHP-7.4
* Pure-Ftpd 1.0.49

 Mononuclear CPU;2G memory ;40 G system disks
 There are no other configurations

 Other errors I recorded below:
```
Deprecated: Array and string offset access syntax with curly braces is deprecated in /www/wwwroot/Wikitten/renderers/Markdown/Markdown.php on line 1799$token{0}

Deprecated: Array and string offset access syntax with curly braces is deprecated in /www/wwwroot/Wikitten/renderers/Markdown/Markdown.php on line 1801$token{1}

Deprecated: Array and string offset access syntax with curly braces is deprecated in /www/wwwroot/Wikitten/renderers/Markdown/MarkdownExtra.php on line 215$element{0}

Deprecated: Array and string offset access syntax with curly braces is deprecated in /www/wwwroot/Wikitten/renderers/Markdown/MarkdownExtra.php on line 217$element{0}

Deprecated: Array and string offset access syntax with curly braces is deprecated in /www/wwwroot/Wikitten/renderers/Markdown/MarkdownExtra.php on line 511$tag{0}

Deprecated: Array and string offset access syntax with curly braces is deprecated in /www/wwwroot/Wikitten/renderers/Markdown/MarkdownExtra.php on line 511$tag{0}

Deprecated: Array and string offset access syntax with curly braces is deprecated in /www/wwwroot/Wikitten/renderers/Markdown/MarkdownExtra.php on line 518

Deprecated: Array and string offset access syntax with curly braces is deprecated in /www/wwwroot/Wikitten/renderers/Markdown/MarkdownExtra.php on line 552

Deprecated: Array and string offset access syntax with curly braces is deprecated in /www/wwwroot/Wikitten/renderers/Markdown/MarkdownExtra.php on line 552

Deprecated: Array and string offset access syntax with curly braces is deprecated in /www/wwwroot/Wikitten/renderers/Markdown/MarkdownExtra.php on line 567

Deprecated: Array and string offset access syntax with curly braces is deprecated in /www/wwwroot/Wikitten/renderers/Markdown/MarkdownExtra.php on line 568

Deprecated: Array and string offset access syntax with curly braces is deprecated in /www/wwwroot/Wikitten/renderers/Markdown/MarkdownExtra.php on line 667

Deprecated: Array and string offset access syntax with curly braces is deprecated in /www/wwwroot/Wikitten/renderers/Markdown/MarkdownExtra.php on line 677

Deprecated: Array and string offset access syntax with curly braces is deprecated in /www/wwwroot/Wikitten/renderers/Markdown/MarkdownExtra.php on line 677

Deprecated: Array and string offset access syntax with curly braces is deprecated in /www/wwwroot/Wikitten/renderers/Markdown/MarkdownExtra.php on line 686

Deprecated: Array and string offset access syntax with curly braces is deprecated in /www/wwwroot/Wikitten/renderers/Markdown/MarkdownExtra.php on line 687

Deprecated: Array and string offset access syntax with curly braces is deprecated in /www/wwwroot/Wikitten/renderers/Markdown/MarkdownExtra.php on line 1074

Deprecated: Array and string offset access syntax with curly braces is deprecated in /www/wwwroot/Wikitten/renderers/Markdown/MarkdownExtra.php on line 1469
```

The above list is not complete, you need to find your own.

Finally, thanks for the software.

**Comment by Gaotianhe** [comment]
> Just like the title. There are many errors like this, I just change it one by one.
> 
> These errors are located in Wikitten/renderers/Markdown/Markdown.php and Wikitten/renderers/Markdown/MarkdownExtra.php.
> 
> The way I alter is changing `{}` to `[]`. That's all the mistakes.
> 
> This is my server configuration:
> BTpanel:It is a simple Installation Panel.
> Through it I install
> 
> * Nginx 1.16.1
> * MySQL 5.5.62
> * PHP-7.4
> * Pure-Ftpd 1.0.49
> 
> Mononuclear CPU;2G memory ;40 G system disks
> There are no other configurations
> 
> Other errors I recorded below:
> 
> ```
> Deprecated: Array and string offset access syntax with curly braces is deprecated in /www/wwwroot/Wikitten/renderers/Markdown/Markdown.php on line 1799$token{0}
> 
> Deprecated: Array and string offset access syntax with curly braces is deprecated in /www/wwwroot/Wikitten/renderers/Markdown/Markdown.php on line 1801$token{1}
> 
> Deprecated: Array and string offset access syntax with curly braces is deprecated in /www/wwwroot/Wikitten/renderers/Markdown/MarkdownExtra.php on line 215$element{0}
> 
> Deprecated: Array and string offset access syntax with curly braces is deprecated in /www/wwwroot/Wikitten/renderers/Markdown/MarkdownExtra.php on line 217$element{0}
> 
> Deprecated: Array and string offset access syntax with curly braces is deprecated in /www/wwwroot/Wikitten/renderers/Markdown/MarkdownExtra.php on line 511$tag{0}
> 
> Deprecated: Array and string offset access syntax with curly braces is deprecated in /www/wwwroot/Wikitten/renderers/Markdown/MarkdownExtra.php on line 511$tag{0}
> 
> Deprecated: Array and string offset access syntax with curly braces is deprecated in /www/wwwroot/Wikitten/renderers/Markdown/MarkdownExtra.php on line 518
> 
> Deprecated: Array and string offset access syntax with curly braces is deprecated in /www/wwwroot/Wikitten/renderers/Markdown/MarkdownExtra.php on line 552
> 
> Deprecated: Array and string offset access syntax with curly braces is deprecated in /www/wwwroot/Wikitten/renderers/Markdown/MarkdownExtra.php on line 552
> 
> Deprecated: Array and string offset access syntax with curly braces is deprecated in /www/wwwroot/Wikitten/renderers/Markdown/MarkdownExtra.php on line 567
> 
> Deprecated: Array and string offset access syntax with curly braces is deprecated in /www/wwwroot/Wikitten/renderers/Markdown/MarkdownExtra.php on line 568
> 
> Deprecated: Array and string offset access syntax with curly braces is deprecated in /www/wwwroot/Wikitten/renderers/Markdown/MarkdownExtra.php on line 667
> 
> Deprecated: Array and string offset access syntax with curly braces is deprecated in /www/wwwroot/Wikitten/renderers/Markdown/MarkdownExtra.php on line 677
> 
> Deprecated: Array and string offset access syntax with curly braces is deprecated in /www/wwwroot/Wikitten/renderers/Markdown/MarkdownExtra.php on line 677
> 
> Deprecated: Array and string offset access syntax with curly braces is deprecated in /www/wwwroot/Wikitten/renderers/Markdown/MarkdownExtra.php on line 686
> 
> Deprecated: Array and string offset access syntax with curly braces is deprecated in /www/wwwroot/Wikitten/renderers/Markdown/MarkdownExtra.php on line 687
> 
> Deprecated: Array and string offset access syntax with curly braces is deprecated in /www/wwwroot/Wikitten/renderers/Markdown/MarkdownExtra.php on line 1074
> 
> Deprecated: Array and string offset access syntax with curly braces is deprecated in /www/wwwroot/Wikitten/renderers/Markdown/MarkdownExtra.php on line 1469
> ```
> 
> The above list is not complete, you need to find your own.
> 
> Finally, thanks for the software.
