### ISSUE TITLE
feature request: added markdown extension

### ISSUE THREAD

**Issue by shallnot** [devaneando/Wikitten#60]
.htm and .html are valid extensions for HTML files. Could a change be made to add .mdown and .markdown as valid MARKDOWN extensions to the existing .md to allow the rederer to render them? Personally I only use .markdown (and .md if the file is from someone else) but I have seen .mdown as a MARKDOWN extension.

**Comment by devaneando** [comment]
I fixed that! Wikitten should now work with .md, .mdown and .markdown files :)
