### ISSUE TITLE
how to  customize css

### ISSUE THREAD

**Issue by gentao123** [devaneando/Wikitten#94]
hi
i write my markdown file use typora local,then upload the .md file to library,but it can't  nicely render. such as line feed.
how can i sove this problem? Could i use my typora css？

thank you very much.

**Comment by devaneando** [comment]
Check [Customize CSS](https://github.com/devaneando/Wikitten/blob/master/library/index.md#customize-css)
I add some changes and now you can add a custom CSS file and Define it in the settings.
It shouldn't be difficult to add your Typora CSS file and tweak it to work with Wikitten.

I hope this helps.
