### ISSUE TITLE
Possible failure when running built-in php server

### ISSUE THREAD

**Issue by shall-ECUAD** [devaneando/Wikitten#98]
In `routing.php` new code has been added:

```
<?php
if (!defined('APP_STARTED')) {
    die('Forbidden!');
}
```

But, wouldn't `APP_STARTED` be false when running`php -S 0.0.0.0:8888 routing.php`? Because, `routing.php` has not had a chance to run `index.php` where `APP_STARTED` is set to true?

Steven

**Comment by devaneando** [comment]
Yeap, you are right.

Since I do not use the builtin web server, I would never notice.

I added a fix and already pushed it.

Just update your master branch and this problem should be gone
